# Generated by Django 4.0.6 on 2022-07-11 00:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='django-uploads/images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ABOUT', 'About'), ('ACCOMMODATION', 'Accommodation'), ('BEACHES', 'Beaches'), ('BIRDS', 'Birds'), ('BOATING', 'Boating'), ('HIKING', 'Hiking'), ('MISC', 'Misc'), ('OCEAN', 'Ocean'), ('STARS', 'Stars'), ('SWIMMING', 'Swimming')], max_length=74),
        ),
    ]
