# Generated by Django 4.0.6 on 2022-08-07 07:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_featureitem_image_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AT-480', 'At 480'), ('ABOUT', 'About'), ('ACCOMMODATION', 'Accommodation'), ('MISC', 'Misc'), ('OCEAN', 'Ocean'), ('OTHER', 'Other')], max_length=43),
        ),
    ]
